version: '3'

services:

  postgres:
    container_name: charactersheet-db
    image: nraymond/charactersheet-db
    build: conf/postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 'daekannal'

  app:
    container_name: charactersheet
    image: nraymond/charactersheet
    build:
      context: .
      args:
        appVersion: ${APP_VERSION}
    ports:
      - 9000:9000
    depends_on:
      - postgres
