version: '2'

networks:
  tcard-network:
    driver: bridge

services:

  tcard-postgres:
    container_name: tcard-postgres
    build: conf/postgres
    networks:
      - tcard-network
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 'daekannal'

  tcard-app:
    container_name: tcard-app
    build: .
    networks:
      - tcard-network
    ports:
      - 9000:9000
    depends_on:
      - tcard-postgres
