version: '3'

services:

  tcard-postgres:
    container_name: tcard-postgres
    build: conf/postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 'daekannal'

  tcard-app:
    container_name: tcard-app
    build: .
    ports:
      - 9000:9000
    depends_on:
      - tcard-postgres
